# -*- python -*-

py_test(
    name = "test_common",
    srcs = ["test_common.py"],
    srcs_version = "PY3",
    deps = [
    	 "//glucometerutils:common",
	 "@abseil_py_archive//absl/testing:parameterized",
    ],
    default_python_version = "PY3",
)
