# SPDX-FileCopyrightText: 2021 The glucometerutils Authors
#
# SPDX-License-Identifier: 0BSD

name: pytest

on:
  push:
  pull_request:

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install libusb-1.0-0-dev libudev-dev
        pip install .[all]
    - name: Test with pytest
      run: |
        pytest -vvv --mypy
